name: Main CI

on:
	push:
		branches:
			- develop
			- prod
		pull_request:
			- develop
			- prod

jobs:
	build:
		runs-on: ubuntu-latest
		strategy:
			matrix:
				node-version: [16.17.0]
	steps:
		- uses: actions/checkout@v2

		- name: Use Node.js ${{ matrix.node-version }}
			uses: action/setup-node@v1
			with:
				node-version: ${{ matrix.node-version }}

		- name: Install dependencies
			run: npm i --legacy-peer-deps
