name: Deploy to Digital ocean droplet
on:
  push:
    branches:
      - prod

jobs:
  build:
    name: Connect to Digital ocean droplet and deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: cd apps/${{ secrets.APP_NAME }} && git checkout prod &&  git pull && npm install && npm run build && pm2 restart ${{ secrets.APP_NAME }}
